sudo: false
language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: XXhDiyv0hENI+nlGMOzKw/2OM99pYnM0YlDzlmYQQv1qIjdCdnPH8JdGxy1vZv3IYK5I1MbXMBDNrXG5IXh311J1J8zzq6547ntxrujTneSLw34AloSqMlgdaZjwKy3n/CAM8i5QVDYSUNKpNAW2Moei4tXvuzAWCPWzDawTDbJzDb1Fpn/t2qzI4P3oPmNiNb87RF+d3r4xrMAExBRTBFeiUwk5Gsk8LL4/I8UXDGqMWmseur38UEYSTeT1Zk4mfcZ3LiyGJkSUQC3XXyUJ6RmLFVQDQF49IXnRmros6lpgm/P2XRFlfk4VTpIuiiMvyCSMM+YEAxmU4PIx71QiBRs42Lp6J9WYQY9oyDtRDxWObG1RufZzBGCZCiJEdKNCISVj/luvSrOXD1aIuDWteIZtVtuAh+2G46S3fds5b8tVo7C3EKdGB5jFL1tStPaSLawM7OW+P2EhzHKaJekFiecdEVu2cUcZ49QzvoBdS+bQyPFClARpQaej70Ei/Qn7KzwE5h7voBtGJd13E5u4BF7UV/TcsZ08ArS0Cb7RjCM1nmCBEyagEqlKuX0CiGvsrf2JiPXvC1S0DdgLB8bjBLT7sOIKhG9t99Ciuobu5vPYkRv1HOq2xzc3CTA5QDst6X7qcbgGvXayBBEpqebC/8nnQ358c58kJw6BhXNTYfo=
  app: shattered-terra
  on:
    repo: apolaskey/shattered-terra
